### ISSUE TITLE
Changing the seperator not possible

### ISSUE THREAD

**Issue by fugohan** [SDN-X/SuperConvert#24]
I saw that the seperator is hard coded to ",". But I would need a ";" as a seperator. Is it possible to implement a seperator option somewhere?

**Comment by esamelzain** [comment]
The Separator has been supported on the latest version, pass `SuperConvertExcelSeperator.SEMICOLON` 
`json.ToCsv(path, fileName,SuperConvertExcelSeperator.SEMICOLON)`

after the file is generated just open a new Excel sheet -> Import -> on the import wizard select semicolon
